# Generated by Django 4.0.1 on 2022-01-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(blank=True, default='cars/car_default.jpg', null=True, upload_to='cars/')),
                ('price', models.IntegerField(null=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('date_changed', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
