# Generated by Django 4.0.1 on 2022-01-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_car_date_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_added',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
