# Generated by Django 4.0.1 on 2022-01-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_car_date_added_alter_car_date_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default='cars/car_default.jpg', null=True, upload_to='cars/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.car')),
            ],
        ),
    ]
