# Generated by Django 4.0.1 on 2022-01-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
    ]
