# Generated by Django 4.0.1 on 2022-01-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.car'),
        ),
    ]
